### ISSUE TITLE
Duda botón detalles

### ISSUE THREAD

**Issue by fabiusinfo** [mivalenz014/INF322#2]
Profe necesito ayuda con el botón detalle, se sabe que al clickear detalles te muestra todos los cursos en una lista, estoy buscando como hacer que solo muestre el detalle del curso en el que clickeas.
![image](https://user-images.githubusercontent.com/26938173/72750947-fe8fdf00-3b9c-11ea-8f52-68dee7e42c62.png)

Es en el archivo horario-clases.ts, la función handleClick() que se ejecuta en el botón detalle que se crea en la tabla.
Lo que intenté fue darle la variable "item" a handleClick() y que mostrara el item por consola, pero deja de funcionar el botón y solo muestra todos los cursos una vez al iniciar la página.

**Comment by mivalenz014** [comment]
Ya está listo
