### ISSUE TITLE
Arreglos en estilo y marcar bloques ocupados

### ISSUE THREAD

**Issue by hvarg** [mivalenz014/INF322#3]
Cuando vemos los detalles de un curso la expansión hace que otros elementos pasen por sobre el footer:

![Screen Shot 2020-02-19 at 23 55 44](https://user-images.githubusercontent.com/15269912/74897254-342f1000-5375-11ea-978f-5bb97b93a5a0.png)

Por otro lado, falta la funcionalidad de marcar los bloques ocupados en el horario, para ello les recomiendo pasar un objeto a su componente, por ejemplo:

```html
<horario-paralelo .ocupado="${this._paralelo[...]}">
</horario-paralelo>
```

En `this._paralelo[...]` pueden guardar toda la información sobre los bloques ocupados y luego, como lo pasamos a la `property` `ocupado` del componente `horario-paralelo` podemos usarlo internamente para marcar los bloques ocupados.

**Comment by mivalenz014** [comment]
Issues completados!
